events {
    worker_connections 4096;
}

http {
    upstream toast_app {
        least_conn;
        server web:3000;
    }

    limit_req_zone $binary_remote_addr zone=university_api_limit:10m rate=50r/s;

    server {
        listen 80;
        server_name _;

        client_max_body_size 50M;

        location / {
            limit_req zone=university_api_limit burst=100 nodelay;
            proxy_pass http://toast_app;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
